export const tokens = { 
    Config: Symbol("Config"),
    ApmClient: Symbol("ApmClient"),
    EmailClient: Symbol("EmailClient"),
    BrapiRepository: Symbol("BrapiRepository"),
    BrapiService: Symbol("BrapiService"),
    IexcloundRepository: Symbol("IexcloundRepository"),
    IexcloundService: Symbol("IexcloundService"),
    InvestRepository: Symbol("InvestRepository"),
    InvestService: Symbol("InvestService"),
    CoreRepository: Symbol("CoreRepository"),
    CoreService: Symbol("CoreService"),
    SystemService: Symbol("SystemService"),
    SystemRepository: Symbol("SystemRepository"),
    Commands: Symbol("Commands"),
};